on:
  push:
    branches: [main]

name: release-please

permissions: {}

jobs:
  release-please:
    if: github.repository_owner == 'mogyugyu'
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@136412a57a7081aa63c935a2cc2918f76c34f514 # v1.11.2
        with:
          app-id: ${{ vars.MOGYUGYU_RELEASE_APP_ID }}
          private-key: ${{ secrets.MOGYUGYU_RELEASE_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release
        with:
          token: ${{ steps.generate_token.outputs.token }}
          config-file: .release-please/release-please-config.json
          manifest-file: .release-please/.release-please-manifest.json
          skip-github-pull-request: ${{ startsWith(github.event.head_commit.message, 'release:') && github.event.head_commit.author.name == format('{0}[bot]', steps.generate_token.outputs.app-slug) }}
